# Site settings
title: Abouba's Portfolio

description: Personal Site and Portfolio
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Abouba 
user_description: Residing in kigali rwanda im a Full stack web & mobile developper and part time graphic designer & bounty hacker ,i love minimalistic and responsive designs with robust back end , i beleive in cross platform prograns with one code base runing on multiple devices thus using modern technologies like  MEAN.JS ,IONIC & ELECTRON
user_title: Full stack web & mobile developer // designer 
email: bitiabt@gmail.com
twitter_username: bitiabt
github_username:  boubex
gplus_username:  Aboubakar Bititaweho

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
