# Site settings
title: Abouba.io   

description: Personal Site and Portfolio
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Abouba _io
user_description: I'm a Fullstack Developer with 3 years of experience bulding cross-platform applications; I work on mobile applications(both android and ios) and web based applications using modern web technologies.
user_title: Developer // Designer 
email: bitiabt@gmail.com
twitter_username: bitiabt
github_username:  boubex
gplus_username:  Aboubakar Bititaweho

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
